### PR TITLE
support recursive download

### PR DESCRIPTION
**Pull request by alienzj**
support recursive download

### CODE REVIEW

**Comment by sdushantha** [comment]
Could you fix this error?
```
$ python3 gitdir.py https://github.com/sindresorhus/ky/tree/master/test
▶ Downloaded 2/8: browser.jsTraceback (most recent call last):
  File "gitdir.py", line 95, in <module>
    main()
  File "gitdir.py", line 70, in main
    urllib.request.urlretrieve(file_url, path)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 246, in urlretrieve
    url_type, path = splittype(url)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/parse.py", line 936, in splittype
    match = _typeprog.match(url)
TypeError: expected string or bytes-like objec
```

**Comment by alienzj** [comment]
```bash
$ python --version
Python 3.7.2

$ python3 gitdir.py https://github.com/sindresorhus/ky/tree/master/test
✔ Finished downloading 8 file(s)
```
I test this on archlinux, can pass.

**Comment by sdushantha** [comment]
@alienzj  I just tested it on Manjaro Linux

```
$ python3 --version
Python 3.7.2

$ python3 gitdir https://github.com/sindresorhus/ky/tree/master/test
▶ Downloaded 2/8: browser.jsTraceback (most recent call last):
  File "gitdir", line 95, in <module>
    main()
  File "gitdir", line 70, in main
    urllib.request.urlretrieve(file_url, path)
  File "/usr/lib/python3.7/urllib/request.py", line 245, in urlretrieve
    url_type, path = splittype(url)
  File "/usr/lib/python3.7/urllib/parse.py", line 956, in splittype
    match = _typeprog.match(url)
TypeError: expected string or bytes-like object
```

**Comment by sdushantha** [comment]
> $ python --version
> Python 3.7.2
> 
> $ python3 gitdir.py https://github.com/sindresorhus/ky/tree/master/test
> ✔ Finished downloading 8 file(s)

@alienzj Hmmm... first your ran `python` but then `python3`. Are you sure that they are the same version?

**Comment by alienzj** [comment]
default

**Comment by alienzj** [comment]
default
@sdushantha same version.

**Comment by sdushantha** [comment]
@alienzj I have no idea whats wrong because I tested it out on MacOS and Manjaro Linux

**Comment by alienzj** [comment]
> @alienzj I have no idea whats wrong because I tested it out on MacOS and Manjaro Linux

@sdushantha I have format code using yapf, could you update it and try again?
Maybe the format have some issues.

**Comment by sdushantha** [comment]
@alienzj WOW it works now!!! :astonished: I guess there was some problem with the indentation

Could you do one more thing?
Since we are downloading another dir, it would be nice the output messages had something to do with it.
**For example:**
Now it shows,
```
✔ Finished downloading 8 file(s)
```
But we actually downloaded 8 files and a folder which has 1 file

**Comment by alienzj** [comment]
@sdushantha Yes, this is a problem.

**Comment by alienzj** [comment]
> @alienzj WOW it works now!!! astonished I guess there was some problem with the indentation
> 
> Could you do one more thing?
> Since we are downloading another dir, it would be nice the output messages had something to do with it.
> **For example:**
> Now it shows,
> 
> ```
> ✔ Finished downloading 8 file(s)
> ```
> 
> But we actually downloaded 8 files and a folder which has 1 file

@sdushantha Yes, this is a problem.

**Comment by alienzj** [comment]
@sdushantha Yes, this is a problem.

**Comment by sdushantha** [comment]
@alienzj Hey, could you please fix the [small issue](https://github.com/sdushantha/gitdir/pull/4#issuecomment-469769473) so that I can merge it? 😄

**Pull request closed without merging**
